version: '3.8'
services:
    db:
        image: postgres
        restart: always
        container_name: "postgresql"
        environment:
            POSTGRES_USER: student
            POSTGRES_PASSWORD: Pan1cal_DEF_111 
            POSTGRES_DB: univerdb
        volumes:
            - ./data:/var/lib/postgresql/data 
            - ./database.sql:/database.sql
        ports:
            - "5432:5432"

    fastapi_db:
        image: postgres
        restart: always
        container_name: "f_db"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: Pan1cal_DEF_111 
            POSTGRES_DB: fastapidb
        volumes:
            - ./f_data:/var/lib/postgresql/f_data 
        ports:
            - "8000:8000"
    api:
        build: ./app
        volumes:
            - ./app:/app
            - ./alembic:/alembic
            - ./alembic.ini:/alembic.ini
        command: python3 ./app/main.py
        ports:
            - "8080:8080"
        depends_on:
            - fastapi_db